language: ruby
rvm:
  - 2.2.1
before_script:
  - curl -O http://nand2tetris.org/software/nand2tetris.zip
  - unzip nand2tetris.zip
  - export EMULATOR=$TRAVIS_BUILD_DIR/nand2tetris/tools/CPUEmulator.sh
script: bundle exec rspec --format documentation
